### PR TITLE
SDL2 support, missing files added

### PR DESCRIPTION
**Pull request by dmitryelj**
Code ported to SDL2 (SDL1 is mostly not supported nowadays)

### CODE REVIEW

**Comment by Frigolit** [comment]
Thanks for the contribution @dmitryelj and sorry for the late reply. Unfortunately this doesn't link for me because of "-lwayland-client" in LDFLAGS as I'm not using Wayland, so it's not available on my system (if I remove it from LDFLAGS everything works fine).
I wouldn't assume this to be necessary as "wayland-client" and "asound" should be dependencies of SDL2, does it work for you without these in LDFLAGS?

**Comment by Frigolit** [comment]
Hi @dmitryelj, due to no reply and me wanting to add SDL2 support to HXEmu, I've taken the SDL2 changes from your pull request and merged it into my tree. I've added you to the readme as a contributor, thank you :)

**Comment by dmitryelj** [comment]
Thanks a lot, it's good to have this code in a working condition :)

But even after converting to SDL2, I was not able to run BASIC or other 3rd party apps, so I switched to that simulator: http://takeda-toshiya.my.coocan.jp/common/index.html 
You can read my review of HX20 here: https://medium.com/geekculture/epson-hx20-testing-the-computer-from-a-german-bundeswehr-af502c70a2ad

**Comment by Frigolit** [comment]
@dmitryelj BASIC works if you do the Initialize step :) I forgot this as well for the longest time now when I've come back to this project and wasted a lot of time trying to figure out what was going on ;D
In a future update it should auto-initialize the system on first run (or simply ship the emulator with a freshly initialized state file) so this won't be necessary.
Nice review, always good to see things happening around the HX-20 :)

**Comment by Frigolit** [comment]
FYI this is currently Left Ctrl + Right Ctrl at the moment. I'm working on implementing a full skin for the emulator ("ui/skin" branch) which will have the full keyboard allowing access to the special keys.

**Pull request closed without merging**
